"""initial revision

Revision ID: 3023fd4bdfe2
Revises:
Create Date: 2026-02-23 23:01:15.838252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3023fd4bdfe2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "CLAUSE_0",
                "SYNTHETIC_1",
                "SYNTHETIC_2",
                "ANALYTIC_3",
                name="accountlevel",
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("ASSET", "LIABILITY", "HYBRID", name="accounttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DISABLED", "ENABLED", name="accountstatus"),
            nullable=True,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bank",
        sa.Column("short_name", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "currency",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "customer",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("second_name", sa.String(), nullable=False),
        sa.Column("middle_name", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deposit",
        sa.Column("bank_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("currency_code", sa.String(), nullable=True),
        sa.Column(
            "interest_term",
            sa.Enum("END_OF_TERM", "MONTHLY", name="interestterms"),
            nullable=False,
        ),
        sa.Column(
            "interest_period_basis",
            sa.Enum("CALENDAR_MONTH", "DEPOSIT_DATE", name="periodanchor"),
            nullable=True,
        ),
        sa.Column(
            "interest_mode",
            sa.Enum("PAYOUT", "CAPITALIZE", name="interestmodes"),
            nullable=True,
        ),
        sa.Column(
            "nominal_rate", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("date_open", sa.Date(), nullable=False),
        sa.Column("date_close", sa.Date(), nullable=True),
        sa.Column("date_last_accrual", sa.Date(), nullable=True),
        sa.Column(
            "principal_value", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "topup_value", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "capitalized_income",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
        sa.Column(
            "paid_income", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "paid_principal", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "accrued_value", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column(
            "balancedays_base",
            sa.Numeric(precision=14, scale=4),
            nullable=True,
        ),
        sa.Column(
            "balancedays_cost",
            sa.Numeric(precision=14, scale=4),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("CLOSED", "ACTIVE", name="depositstatus"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["bank.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation",
        sa.Column("deposit_id", sa.Integer(), nullable=True),
        sa.Column(
            "operation_type",
            sa.Enum(
                "OPEN",
                "TOPUP",
                "WITHDRAWAL",
                "INTEREST_ACCRUAL",
                "INTEREST_CAPITALIZE",
                "INTEREST_PAYOUT",
                "CLOSE",
                "EARLY_CLOSE",
                "CORRECTION",
                "CHANGE_DURATION",
                "CHANGE_RATE",
                name="depositoperationtype",
            ),
            nullable=False,
        ),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("operation_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("payload_json", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deposit_id"],
            ["deposit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column(
            "transaction_type",
            sa.Enum(
                "INFLOW",
                "OUTFLOW",
                "INTEREST_ACCRUAL",
                "INTEREST_CAPITALIZE",
                "INTEREST_PAYOUT",
                "FEE",
                "CORRECTION",
                "REVERSAL",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "product_type",
            sa.Enum(
                "DEPOSIT_TERM",
                "DEPOSIT_SAVINGS",
                "CARD_DEBIT",
                "CARD_CREDIT",
                "MORTGAGE",
                name="producttype",
            ),
            nullable=False,
        ),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "POSTED", "REVERSED", name="transactionstatus"),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["deposit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entry",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("debit_account_id", sa.Integer(), nullable=False),
        sa.Column("credit_account_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credit_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["debit_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry")
    op.drop_table("transaction")
    op.drop_table("operation")
    op.drop_table("deposit")
    op.drop_table("customer")
    op.drop_table("currency")
    op.drop_table("bank")
    op.drop_table("account")
    # ### end Alembic commands ###
