"""empty message

Revision ID: 8d566e932535
Revises: e19ccf6d946c
Create Date: 2025-11-22 13:55:12.280681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d566e932535'
down_revision: Union[str, None] = 'e19ccf6d946c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('interest_basis', sa.Enum('CALENDAR_MONTH', 'OPEN_DATE', 'DAYLY', name='interestbasis'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'interest_basis')
    # ### end Alembic commands ###
