"""empty message

Revision ID: 98d1ef8ea87e
Revises: 8d566e932535
Create Date: 2025-11-23 07:11:46.691801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d1ef8ea87e'
down_revision: Union[str, None] = '8d566e932535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('capitalized_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('deposit', sa.Column('withdraw', sa.Enum('NOT_ALLOWED', 'ALLOWED', 'LIMITED', name='withdrawal'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'withdraw')
    op.drop_column('deposit', 'capitalized_value')
    # ### end Alembic commands ###
