"""empty message

Revision ID: bfefff9d7e4d
Revises: 
Create Date: 2025-11-21 15:21:30.501585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfefff9d7e4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('second_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date_open', sa.Date(), nullable=False),
    sa.Column('date_close', sa.Date(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('principal_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('topup_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('nominal_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interest_term', sa.Enum('END_OF_TERM', 'MONTHLY_COMPOUND', 'MONTHLY_PAYOUT', name='interestterms'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSE', name='depositstatus'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_payment', sa.Date(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='incomestatus'), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    op.drop_table('deposit')
    op.drop_table('customer')
    op.drop_table('currency')
    op.drop_table('bank')
    # ### end Alembic commands ###
