@startuml depo_erd
'https://plantuml.com/object-diagram
'Opt+D to Preview

<style>
    document {
        BackGroundColor Linen
    }
    root {
        FontColor #?black:white
        LineColor gray
    }
</style>

title BANK_DEPOSITS_ERD

object BankDeposit {
    id: PK
    bank_name: str
    client_name: str
    description: str
    duration: int
    date_open: date
    date_close: date
    principal_value: Decimal
    topup_value: Decimal
    nominal_rate: Decimal
    interest_term: enum
    status: enum
    incomes[]
}

object Income {
    id: PK
    value
    period
    date_payment
    deposit_id: FK
}

object JournalEntry {
    id: PK
    date
    description
    document_id
    entryLines[]
}

object EntryLine {
    id
    entry_id
    debit_acc_id
    credit_acc_id
    amount
}

object  Account {
    id: PK
    accHierarchyId: FK
    journalEntries[]
    Kt[]
    Balance
}

object AccHierarchy {
    id: PK
    level
    number
    name
    type
    accHierarchyId: FK
}

object Customer {
    id
    first_name
    second_name
    middle_name
}

object Bank {
    id
    short_name
    full_name
    address
    status
}

object Currency {
    id: PK
    short_name
    full_name
    country
}

BankDeposit::income - Income::id

@enduml
