@startuml depo_erd
'https://plantuml.com/object-diagram
'Opt+D to Preview

<style>
    document {
        BackGroundColor Linen
    }
    root {
        FontColor #?black:white
        LineColor gray
    }
</style>

title BANK_DEPOSITS_ERD

object BankDeposit {
    id: PK
    bank_name: str
    customer_name: str
    currency_name: str
    description: str
    duration: int
    date_open: date
    date_close: date
    principal_value: Decimal
    capitalized_value: Decimal
    topup_value: Decimal
    nominal_rate: Decimal
    interest_term: enum
    interest_basis: enum
    status: enum
    incomes[]
    operations[]
}

object Income {
    id: PK
    value
    period
    date_payment
    deposit_id: FK
}

object Operation {
    id
    deposit_id
    transaction_id
    operation_type
    amount
    operation_date
    description
}


object Customer {
    id
    first_name
    second_name
    middle_name
}


object Bank {
    id
    short_name
    full_name
    address
    status
}


object Currency {
    id: PK
    short_name
    full_name
    country
}


object  Account {
    id: PK
    name
    code
    level
    type
    status
    parent_id: FK
    children_id: FK
    transactions[]
}


object Entry {
    id
    transaction_id
    debit_id
    credit_id
    amount
    date
    description
}


object Transaction {
    id: PK
    operation_id: FK
    transaction_type
    product_type
    product_id
    status
    posted_at
    description
    entries[]
}


BankDeposit::income - Income::id
BankDeposit::bank_name - Bank::id
BankDeposit::customer_name - Customer::id
BankDeposit::currency_name - Currency::id

JournalEntry::entryLines - EntryLine::id
EntryLine::debit_acc_id - Account::id
EntryLine::credit_acc_id - Account::id
Account::accHierarchyId - AccHierarchy::id


@enduml
