@startuml depo_erd
'https://plantuml.com/object-diagram
'Opt+D to Preview

<style>
    document {
        BackGroundColor Linen
    }
    root {
        FontColor #?black:white
        LineColor gray
    }
</style>

title BANK_DEPOSITS_ERD

object BankDeposit {
    id: PK
    bankName
    clientName
    description
    duration
    dateOpen
    dateClose
    faceValue
    interestRate
    incomes[]
}

object Income {
    id: PK
    depositId
    value
    datePayment
}

object JournalEntry {
    id: PK
    date
    amount
    units
    debit
    credit
    description
}

BankDeposit::income - Income::id


@enduml
